package com.medialab.beans;

public enum MediaLABResponse {
	STICKERS_RETRIEVE_SUCESS,
	STICKER_ADDED,
	ALREADY_HAVE_STICKER,
	TRADE_LIMIT,
	TRADE_ALREADY_CREATED,
	TRADE_ALREADY_CLOSED,
	NO_STICKERS_FOUND,
	INITIATOR_DOUBLE_NOT_FOUND,
	RESPONDENT_DOUBLE_NOT_FOUND,
	NO_MATCHES_FOUND,
	USER_NOT_FOUND,
	VIDEO_NOT_FOUND,
	ALBUM_NOT_FOUND,
	PLAYER_NOT_FOUND,
	TRADE_NOT_FOUND,
	SUCCESS,
	UNKOWN_ERROR;
}
